### ISSUE TITLE
Installation issue on Ubuntu

### ISSUE THREAD

**Issue by ganesh3** [noiselabs/box-linux-sync#22]
Hi,

Getting the following error post cloning from Git on Ubuntu 16.04

./box-sync setup
Traceback (most recent call last):
  File "./box-sync", line 51, in <module>
    from noiselabs.box.main import box_main
  File "/home/ganesh/box-linux-sync/src/noiselabs/__init__.py", line 22, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
ImportError: No module named pkg_resources

Regards

**Comment by micahculpepper** [comment]
@ganesh3 I'm not a maintainer on this project, but I happened to see your post.

'pkg_resources' is a Python library that should be installed on your system, but apparently isn't. To fix it, try this:

```
sudo apt-get install python python-pip
sudo pip install setuptools --upgrade
```

**Comment by shivasurya** [comment]
thanks this helped :)
